ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/bmi160-new
ccflags-y += -Wno-error

obj-y	:=  bmi160_gyro.o
